In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding= 'latin1', sep=';')
df.head(3)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3

In [3]:
df.tail(2)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37997,167,6,2026,2026m06,43,5,Paraty,3303807,Interior,1,...,4.0,0.0,14,1,1,0,0,0,198,2
37998,168,6,2026,2026m06,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,4,0,0,0,0,0,32,2

In [4]:
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37999 entries, 0 to 37998
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37999 non-null  int64
 1   mes                         37999 non-null  int64
 2   ano                         37999 non-null  int64
 3   mes_ano                     37999 non-null  str
 4   aisp                        37999 non-null  int64
 5   risp                        37999 non-null  int64
 6   munic                       37999 non-null  str
 7   mcirc                       37999 non-null  int64
 8   regiao                      37999 non-null  str
 9   hom_doloso                  37999 non-null  int64
 10  lesao_corp_morte            37999 non-null  int64
 11  latrocinio                  37999 non-null  int64
 12  cvli                        37999 non-null  int64
 13  hom_por_interv_policial     37999 non-null  int64
 14  feminicidio                 2877 non-null   float64
 15  letalidade_violenta         37999 non-null  int64
 16  tentat_hom                  37999 non-null  int64
 17  tentativa_feminicidio       2877 non-null   float64
 18  lesao_corp_dolosa           37999 non-null  int64
 19  estupro                     37999 non-null  int64
 20  hom_culposo                 37999 non-null  int64
 21  lesao_corp_culposa          37999 non-null  int64
 22  roubo_transeunte            37999 non-null  int64
 23  roubo_celular               37999 non-null  int64
 24  roubo_em_coletivo           37999 non-null  int64
 25  roubo_rua                   37999 non-null  int64
 26  roubo_veiculo               37999 non-null  int64
 27  roubo_carga                 37999 non-null  int64
 28  roubo_comercio              37999 non-null  int64
 29  roubo_residencia            37999 non-null  int64
 30  roubo_banco                 37999 non-null  int64
 31  roubo_cx_eletronico         37980 non-null  float64
 32  roubo_conducao_saque        37999 non-null  int64
 33  roubo_apos_saque            37999 non-null  int64
 34  roubo_bicicleta             20610 non-null  float64
 35  outros_roubos               37999 non-null  int64
 36  total_roubos                37999 non-null  int64
 37  furto_veiculos              37999 non-null  int64
 38  furto_transeunte            37999 non-null  int64
 39  furto_coletivo              37999 non-null  int64
 40  furto_celular               37999 non-null  int64
 41  furto_bicicleta             20610 non-null  float64
 42  outros_furtos               37999 non-null  int64
 43  total_furtos                37999 non-null  int64
 44  sequestro                   37999 non-null  int64
 45  extorsao                    37999 non-null  int64
 46  sequestro_relampago         37999 non-null  int64
 47  estelionato                 37999 non-null  int64
 48  apreensao_drogas            37999 non-null  int64
 49  posse_drogas                33353 non-null  float64
 50  trafico_drogas              33353 non-null  float64
 51  apreensao_drogas_sem_autor  33353 non-null  float64
 52  recuperacao_veiculos        37999 non-null  int64
 53  apf                         33353 non-null  float64
 54  aaapai                      33353 non-null  float64
 55  cmp                         33353 non-null  float64
 56  cmba                        33353 non-null  float64
 57  ameaca                      37999 non-null  int64
 58  pessoas_desaparecidas       37999 non-null  int64
 59  encontro_cadaver            37999 non-null  int64
 60  encontro_ossada             37999 non-null  int64
 61  pol_militares_mortos_serv   37999 non-null  int64
 62  pol_civis_mortos_serv       37999 non-null  int64
 63  registro_ocorrencias        37999 non-null  int64
 64  fase                        37999 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.8 MB

In [6]:
df.head(2)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3

In [7]:
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp = df_furto_cel_dp.sort_values(by='furto_celular', ascending = False)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

In [38]:
df_roubo_rua_dp = df.groupby('cisp')['roubo_rua'].sum().reset_index()
df_roubo_rua_dp = df_roubo_rua_dp.sort_values(by='roubo_rua', ascending = False)
df_roubo_rua_dp

     cisp  roubo_rua
52     59      87859
57     64      64737
30     34      58326
25     29      50126
65     74      47594
..    ...        ...
131   157         16
130   156         11
94    111          7
77     92          6
129   155          5

[138 rows x 2 columns]

In [9]:
array_roubo_rua_dp = np.array(df_roubo_rua_dp['roubo_rua'])

In [39]:

media = np.mean(array_roubo_rua_dp)
mediana = np.median(array_roubo_rua_dp)
q1 = np.percentile(array_roubo_rua_dp, 25)
q2 = np.percentile(array_roubo_rua_dp, 50)
q3 = np.percentile(array_roubo_rua_dp,75)

In [11]:
print (f'Média {media}\nMediana {mediana}\nQ1 {q1}\nQ2 {q2}\nQ3 {q3}')

Média 13035.13768115942
Mediana 5333.5
Q1 252.75
Q2 5333.5
Q3 23408.75

In [12]:
distancia = (media - mediana) / mediana
print(distancia)
print(f'{distancia:.2%}')

1.4440119398442712
144.40%

In [13]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp = df_aaapai_dp.sort_values(by='aaapai', ascending = False)
df_aaapai_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [14]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False)
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [15]:
df_capital = df[df['munic'] == 'Rio de Janeiro'] #usando sistema de filtro, assim seria na unha. dfdentro de munic só quero rio de janeiro
df_capital

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37898,40,6,2026,2026m06,9,2,Rio de Janeiro,3304557,Capital,3,...,8.0,3.0,38,1,0,0,0,0,617,2
37899,41,6,2026,2026m06,18,2,Rio de Janeiro,3304557,Capital,1,...,9.0,3.0,22,5,0,0,0,0,814,2
37900,42,6,2026,2026m06,31,2,Rio de Janeiro,3304557,Capital,4,...,12.0,2.0,99,7,1,0,0,0,1319,2
37901,43,6,2026,2026m06,27,2,Rio de Janeiro,3304557,Capital,0,...,6.0,1.0,96,7,0,0,0,0,720,2
37902,44,6,2026,2026m06,3,1,Rio de Janeiro,3304557,Capital,0,...,15.0,3.0,46,6,0,0,0,0,790,2

In [16]:
df_capital = df.loc[df['munic'] == 'Rio de Janeiro']

#usando .query() - sintaxw alternativa mais legível
df_capital = df.query("munic == 'Rio de Janeiro'")

df_furto_cel_dp_capital = df_capital.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp_capital = df_furto_cel_dp_capital.sort_values(by='furto_celular', ascending=False)
df_furto_cel_dp_capital

    cisp  furto_celular
12    16          26111
2      5          25440
10    14          18822
8     12          17537
0      1          16127
5      9          15278
6     10          14773
14    18          14436
1      4          14247
28    32          12833
31    35          12231
15    19           8899
13    17           8701
25    29           8223
38    42           8132
9     13           7804
19    23           7360
11    15           7261
17    21           7040
30    34           6971
33    37           6669
3      6           6617
29    33           6185
18    22           5770
32    36           5596
37    41           5458
16    20           5357
20    24           4758
23    27           4708
22    26           4162
24    28           4126
21    25           4120
40    44           3779
26    30           3762
34    38           3142
35    39           2968
39    43           2869
36    40           2353
27    31           1744
4      7           1630
7     11            410
41    45             73

In [17]:
munic_pedido = ['Belford Roxo', 'Nova Iguaçu', 'Queimados']

df_bel_nov_quei = df.loc[df["munic"].isin(munic_pedido) & (df['ano'] == 2025)] #fez a lista com munícipio para filtar eses 3 munic data frame.locdf procurar em munic dentro de munic pedido isin, dentro de, & add filtro ano.

df_furto_cel_dp_belford = df_bel_nov_quei.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp_belford = df_furto_cel_dp_belford.sort_values(by='furto_celular', ascending=False)
df_furto_cel_dp_belford

   cisp  furto_celular
0    52            519
4    58            188
3    56            123
1    54            112
2    55             96

In [18]:
array_furto_cel_dp = np.array(df_furto_cel_dp['furto_celular'])
array_furto_cel_dp

array([26111, 25440, 18822, 17537, 16127, 15278, 14773, 14436, 14247,
       12833, 12231,  8899,  8849,  8701,  8342,  8223,  8132,  7804,
        7360,  7261,  7040,  6971,  6669,  6617,  6185,  5770,  5655,
        5596,  5458,  5357,  5041,  4979,  4758,  4755,  4708,  4652,
        4162,  4126,  4120,  4052,  3885,  3795,  3779,  3762,  3531,
        3421,  3376,  3286,  3142,  2997,  2968,  2869,  2707,  2681,
        2611,  2416,  2393,  2353,  2322,  2207,  2158,  2150,  2139,
        2132,  2089,  1836,  1836,  1825,  1744,  1714,  1663,  1630,
        1546,  1485,  1473,  1441,  1390,  1376,  1309,  1250,  1149,
        1096,  1050,  1042,  1035,   907,   836,   822,   810,   752,
         743,   662,   654,   633,   632,   626,   583,   565,   516,
         513,   506,   499,   461,   453,   451,   442,   410,   405,
         385,   374,   369,   362,   357,   304,   302,   260,   244,
         238,   213,   206,   203,   197,   172,   167,   155,   147,
         129,   124,   116,   111,    90,    83,    73,    73,    65,
          56,    55,    47])

In [19]:
media = np.mean(array_furto_cel_dp)
mediana = np.median(array_furto_cel_dp)
q1 = np.percentile(array_furto_cel_dp, 25)
q2 = np.percentile(array_furto_cel_dp, 50)
q3 = np.percentile(array_furto_cel_dp,75)
iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)

print (f'Q1 {q1}')
print (f'Q2 {q2}')
print (f'Q3 {q3}')
print (f'Média {media}')
print (f'Mediana {mediana}')
print (f'Distancia {distancia:.2%}')
print(f'Limite Superior {limite_superior}')
print(f'Limite Inferior {limite_inferior}')

Q1 455.0
Q2 1729.0
Q3 4694.0
Média 3534.014492753623
Mediana 1729.0
Distancia 144.40%
Limite Superior 11052.5
Limite Inferior -5903.5

In [20]:
outlier_furto_cel_dp = df_furto_cel_dp.loc[df_furto_cel_dp['furto_celular'] > limite_superior]

outlier_furto_cel_dp

    cisp  furto_celular
12    16          26111
2      5          25440
10    14          18822
8     12          17537
0      1          16127
5      9          15278
6     10          14773
14    18          14436
1      4          14247
28    32          12833
31    35          12231

In [21]:
print(f'Media {media}')
print(f'Mediana {mediana}')
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

Media 3534.014492753623
Mediana 1729.0
Q1: 455.0
Q2: 1729.0
Q3: 4694.0

In [22]:
df_furto_cel_acima_q3 = df_furto_cel_dp.loc[df_furto_cel_dp['furto_celular'] > q3]
df_furto_cel_acima_q3

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
5       9          15278
6      10          14773
14     18          14436
1       4          14247
28     32          12833
31     35          12231
15     19           8899
52     59           8849
13     17           8701
67     76           8342
25     29           8223
38     42           8132
9      13           7804
19     23           7360
11     15           7261
17     21           7040
30     34           6971
33     37           6669
3       6           6617
29     33           6185
18     22           5770
45     52           5655
32     36           5596
37     41           5458
16     20           5357
68     77           5041
104   126           4979
20     24           4758
65     74           4755
23     27           4708

In [23]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False)
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [24]:
array_roubo_veiculo_dp = np.array(df_roubo_veiculo_dp['roubo_veiculo'])
array_furto_cel_dp

array([26111, 25440, 18822, 17537, 16127, 15278, 14773, 14436, 14247,
       12833, 12231,  8899,  8849,  8701,  8342,  8223,  8132,  7804,
        7360,  7261,  7040,  6971,  6669,  6617,  6185,  5770,  5655,
        5596,  5458,  5357,  5041,  4979,  4758,  4755,  4708,  4652,
        4162,  4126,  4120,  4052,  3885,  3795,  3779,  3762,  3531,
        3421,  3376,  3286,  3142,  2997,  2968,  2869,  2707,  2681,
        2611,  2416,  2393,  2353,  2322,  2207,  2158,  2150,  2139,
        2132,  2089,  1836,  1836,  1825,  1744,  1714,  1663,  1630,
        1546,  1485,  1473,  1441,  1390,  1376,  1309,  1250,  1149,
        1096,  1050,  1042,  1035,   907,   836,   822,   810,   752,
         743,   662,   654,   633,   632,   626,   583,   565,   516,
         513,   506,   499,   461,   453,   451,   442,   410,   405,
         385,   374,   369,   362,   357,   304,   302,   260,   244,
         238,   213,   206,   203,   197,   172,   167,   155,   147,
         129,   124,   116,   111,    90,    83,    73,    73,    65,
          56,    55,    47])

In [25]:
media = np.mean(array_roubo_veiculo_dp)
mediana = np.median(array_roubo_veiculo_dp)
q1 = np.percentile(array_roubo_veiculo_dp, 25)
q2 = np.percentile(array_roubo_veiculo_dp, 50)
q3 = np.percentile(array_roubo_veiculo_dp, 75)

In [26]:
print (f'Média {media}\nMediana {mediana}\nQ1 {q1}\nQ2 {q2}\nQ3 {q3}')

Média 5250.840579710145
Mediana 1227.0
Q1 103.75
Q2 1227.0
Q3 8117.5

In [27]:
df_roubo_veiculo_dp_q3_acima = df_roubo_veiculo_dp.loc[df_roubo_veiculo_dp ['roubo_veiculo'] > q3]
df_roubo_veiculo_dp_q3_acima

    cisp  roubo_veiculo
52    59          37780
57    64          32839
35    39          29663
23    27          27920
30    34          27543
47    54          24945
53    60          20696
34    38          20044
17    21          19790
31    35          19422
36    40          19403
65    74          18414
29    33          18069
25    29          16895
51    58          16351
45    52          15653
18    22          15193
27    31          15122
40    44          14912
63    72          14212
64    73          14000
26    30          12866
50    57          12516
20    24          12108
49    56          12019
21    25          11076
24    28          11057
19    23          10803
66    75          10165
55    62           9279
16    20           9124
28    32           8694
69    78           8571
46    53           8567
62    71           8203

In [28]:
print(f'Média roubo {media}\nMediana roubo {mediana}')

Média roubo 5250.840579710145
Mediana roubo 1227.0

In [29]:
distancia = (media - mediana) / mediana
print(distancia)
print(f'{distancia:.2%}')

3.279413675395391
327.94%

In [30]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp = df_aaapai_dp.sort_values(by='aaapai', ascending = False)
df_aaapai_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [31]:
array_aaapai_dp = np.array(df_aaapai_dp['aaapai'])
array_aaapai_dp

array([3713., 3657., 3365., 3349., 3218., 3030., 2858., 2842., 2749.,
       2702., 2696., 2297., 2271., 2260., 2140., 2085., 2058., 2043.,
       1894., 1815., 1812., 1798., 1748., 1675., 1653., 1647., 1637.,
       1612., 1553., 1546., 1546., 1405., 1362., 1360., 1277., 1272.,
       1242., 1236., 1216., 1187., 1184., 1140., 1133., 1128., 1112.,
       1081., 1049., 1015.,  983.,  982.,  939.,  891.,  885.,  882.,
        877.,  830.,  818.,  803.,  802.,  799.,  787.,  778.,  775.,
        752.,  744.,  742.,  703.,  702.,  690.,  683.,  636.,  631.,
        610.,  599.,  589.,  558.,  536.,  518.,  505.,  408.,  395.,
        391.,  387.,  386.,  352.,  347.,  329.,  326.,  323.,  320.,
        318.,  318.,  313.,  311.,  311.,  301.,  288.,  287.,  287.,
        283.,  277.,  273.,  231.,  221.,  204.,  189.,  174.,  170.,
        163.,  161.,  154.,  140.,  114.,  112.,   95.,   93.,   89.,
         87.,   86.,   75.,   68.,   66.,   63.,   63.,   62.,   45.,
         45.,   44.,   39.,   36.,   33.,   28.,   27.,   19.,   16.,
         14.,   13.,   12.])

In [32]:
media = np.mean(array_aaapai_dp)
mediana = np.median(array_aaapai_dp)
q1 = np.percentile(array_aaapai_dp, 25)
q2 = np.percentile(array_aaapai_dp, 50)
q3 = np.percentile(array_aaapai_dp, 75)
print (f'Média {media}\nMediana {mediana}\nQ1 {q1}\nQ2 {q2}\nQ3 {q3}')

Média 909.268115942029
Mediana 686.5
Q1 223.5
Q2 686.5
Q3 1275.75

In [33]:
distancia = (media - mediana) / mediana
print(distancia)
print(f'{distancia:.2%}')

0.3244983480583088
32.45%

In [ ]:
df_capital = df.loc[df['munic'] == 'Rio de Janeiro']

df_furto_veiculo_dp_capital = df_capital.groupby('cisp')['furto_veiculos'].sum().reset_index()
df_furto_veiculo_dp_capital = df_furto_veiculo_dp_capital.sort_values(by='furto_veiculos', ascending=False)
df_furto_veiculo_dp_capital

In [ ]:
array_furto_veiculo_dp_capital = np.array(df_furto_veiculo_dp_capital['furto_veiculos'])
array_furto_veiculo_dp_capital

In [ ]:
media = np.mean(array_furto_veiculo_dp_capital)
mediana = np.median(array_furto_veiculo_dp_capital)
q1 = np.percentile(array_furto_veiculo_dp_capital, 25)
q2 = np.percentile(array_furto_veiculo_dp_capital, 50)
q3 = np.percentile(array_furto_veiculo_dp_capital,75)
iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)

print (f'Q1 {q1}')
print (f'Q2 {q2}')
print (f'Q3 {q3}')
print (f'Média {media}')
print (f'Mediana {mediana}')
print (f'Distancia {distancia:.2%}')
print(f'Limite Superior {limite_superior}')
print(f'Limite Inferior {limite_inferior}')

In [42]:
dp_outlier_sup_furto_veiculo = df_furto_veiculo_dp_capital.loc[df_furto_veiculo_dp_capital['furto_veiculos'] > limite_superior]
dp_outlier_sup_furto_veiculo

    cisp  furto_veiculos
31    35           14732
12    16           12613
23    27           12113

In [44]:
dp_outlier_inf_furto_veiculo = df_furto_veiculo_dp_capital.loc[df_furto_veiculo_dp_capital['furto_veiculos'] < limite_inferior]
dp_outlier_inf_furto_veiculo

Empty DataFrame
Columns: [cisp, furto_veiculos]
Index: []